### PR TITLE
sync upstream v0.1.1

### PR DESCRIPTION
**Pull request by fsx950223**
Sync Meta main branch to rocm branch.
Port new profiler to rocm backend and fix bugs in common code.
Lint code.

### CODE REVIEW

**Comment by carlushuang** [comment]
`gen_profiler()` seems broken in `gemm_common.gemm` for rocm backend. Please help fix this and check if still have further broken pieces

**Comment by carlushuang** [comment]
Still fail. I think we need to understand the profiler design of v0.1.1

**Comment by illsilin** [comment]
Hi guys. I created a branch sync_version0.1.1 in the rocm repo and merged your changes with the latest version of the amd-develop branch so that it would run the CI build. You can see the results here:

https://github.com/ROCmSoftwarePlatform/AITemplate/actions/runs/3493993183 

At the bottom of the page there's a "test results" archive with the log files from the tests. You can download and look at those logs. There are a bunch of errors like 

RuntimeError: Failed to extract profiler result for ['./tmp/profiler/gemm_rcr_bias/gemm_1_hhh_TNT_256_256_128_32_8_8_32_32_4_2_A', '1', '1000', '2048', '1']
2022-11-18 05:08:46,892 WARNING <aitemplate.backend.profiler_runner> Profiler failure!
Profiler stdout: 
Profiler stderr: terminate called after throwing an instance of 'std::runtime_error'
  what():  wrong! DeviceGemmMultipleD_Xdl_CShuffle<256, 128, 256, 32, 8, 8, Default> with the specified compilation parameters does not support this Gemm problem.

However, surprisingly, most of the profiling results are still there and look consistent with the baseline. All except the stable diffusion. That one crashed:

AttributeError: 'Model' object has no attribute '_allocated_ait_data'

Please feel free to use the rocm/sync_version0.1.1 branch for further debugging, since it will trigger the CI builds and you'll be able to track the progress automatically.

**Comment by illsilin** [comment]
Oh, I just noticed that the stable diffusion benchmark is fixed with the latest commit:

https://github.com/ROCmSoftwarePlatform/AITemplate/actions/runs/3495078687/jobs/5851452115

Good job guys!

**Review by carlushuang — APPROVED** [review]
LGTM

**Pull request merged**
